---
powerdns_authoritative: true
powerdns_authoritative_recursor: 127.0.0.1:5300
powerdns_recursor_daemon: true
powerdns_recursor: true
powerdns_recursor_local_port: 5300

nip_repo: https://github.com/gites/nip.io
nip_tag: v1.0
nip_domains:
  - woop.sh
  - lcl.io
nip_dir: /opt/nip.io
nip_ttl: 432000
nip_default_ipaddr: 127.0.0.1
nip_hostmaster: hostmaster@{{ item }}
nip_ns: ns1.{{ item }}
nip_nameservers:
  - ns1.{{ item }}=127.0.0.1
  - ns2.{{ item }}=127.0.0.1
